[package]
name = "rust_mail"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.0.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[lib]
path = "src/lib.rs"
[[bin]]
path = "src/main.rs"
name = "rust_mail"

[dev-dependencies]
reqwest = "0.11"